version: '3'

services:
  db:
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "session_data:/data"


volumes:
  db_data:
  session_data: